insert into CUSTOMER (CUSTOMER_NAME, CUSTOMER_ADDRESS, PHONE_NO, CART_ID) values ('Hung', 'Binh Dinh','0000000000',null );
insert into CUSTOMER (CUSTOMER_NAME, CUSTOMER_ADDRESS, PHONE_NO, CART_ID) values ('Kien', 'Quang Ngai','0000000001',null);
insert into CUSTOMER (CUSTOMER_NAME, CUSTOMER_ADDRESS, PHONE_NO, CART_ID) values ('Hieu', 'Khanh Hoa','0000000002',null);
insert into CUSTOMER (CUSTOMER_NAME, CUSTOMER_ADDRESS, PHONE_NO, CART_ID) values ('Hao', 'Binh Thuan','0000000003',null);
insert into CUSTOMER (CUSTOMER_NAME, CUSTOMER_ADDRESS, PHONE_NO, CART_ID) values ('Thanh', 'Dong Nai','0000000001',null);

insert into PRODUCT(NAME_PRODUCT, PRODUCT_TYPE, SIZE, QUANTITY , PRICE) values ('NIKE', 'SP','M',100, 1000.00);
insert into PRODUCT(NAME_PRODUCT, PRODUCT_TYPE, SIZE, QUANTITY , PRICE) values ('NIKE', 'SP','L',100, 1000.00);
insert into PRODUCT(NAME_PRODUCT, PRODUCT_TYPE, SIZE, QUANTITY , PRICE) values ('NIKE', 'SP','S',100, 1000.00);
insert into PRODUCT(NAME_PRODUCT, PRODUCT_TYPE, SIZE, QUANTITY , PRICE) values ('ADIDAS', 'RN','L',100, 1000.00);
insert into PRODUCT(NAME_PRODUCT, PRODUCT_TYPE, SIZE, QUANTITY , PRICE) values ('ADIDAS', 'RN','M',100, 2000.00);
insert into PRODUCT(NAME_PRODUCT, PRODUCT_TYPE, SIZE, QUANTITY , PRICE) values ('ADIDAS', 'RN','S',100, 3000.00);
insert into PRODUCT(NAME_PRODUCT, PRODUCT_TYPE, SIZE, QUANTITY , PRICE) values ('PUMA', 'FS','XL',100, 500.00);
insert into PRODUCT(NAME_PRODUCT, PRODUCT_TYPE, SIZE, QUANTITY , PRICE) values ('PUMA', 'FS','L',100, 300.00);
insert into PRODUCT(NAME_PRODUCT, PRODUCT_TYPE, SIZE, QUANTITY , PRICE) values ('PUMA', 'FS','M',100, 200.00);
insert into PRODUCT(NAME_PRODUCT, PRODUCT_TYPE, SIZE, QUANTITY , PRICE) values ('PAN', 'SC','M',100, 1500.00);